name: ruby

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/ruby

    steps:
      - uses: actions/checkout@v2.3.1

      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.7.1'

      - name: Run tests
        run: |
          bundle
          rake spec
